"""default data

Revision ID: 77d5d9ff936f
Revises: 96f137f62ede
Create Date: 2020-01-05 17:04:12.068482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d5d9ff936f'
down_revision = '96f137f62ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_data')
    # ### end Alembic commands ###
